### ISSUE TITLE
Ignore registration failure for resteasy servlet

### ISSUE THREAD

**Issue by dsharinov** [resteasy/resteasy-spring-boot#314]
When deploying application on Tomcat, I'm getting the following error:
```
java.lang.IllegalStateException: Failed to register 'servlet ResteasyServlet' on the servlet context. Possibly already registered?
		at org.springframework.boot.web.servlet.DynamicRegistrationBean.register(DynamicRegistrationBean.java:122)
		at org.springframework.boot.web.servlet.RegistrationBean.onStartup(RegistrationBean.java:52)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:241)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:197)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext
```
Executable war file runs without any issues. 
If when debugging, I set `ignoreRegistrationFailure` to **true** in `ResteasyApplicationBuilder#build` the application is deployed successfully.
I checked the code for Jersey, and it's also configured to ignore registration failures. 
I couldn't find an easy way to get ride of the error.

**Comment by liweinan** [comment]
@dsharinov Could you please provide a sample project to reproduce this on Github?

**Comment by dsharinov** [comment]
@liweinan 
https://github.com/dsharinov/resteasy-example
That's a simple example that fails with the error when deployed on Tomcat but runs successfully as a Spring Boot application.
```
	Caused by: java.lang.IllegalStateException: Failed to register 'servlet com.example.resteasy.ResteasyServlet' on the servlet context. Possibly already registered?
		at org.springframework.boot.web.servlet.DynamicRegistrationBean.register(DynamicRegistrationBean.java:122)
		at org.springframework.boot.web.servlet.RegistrationBean.onStartup(RegistrationBean.java:52)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:241)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:197)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
```

**Comment by liweinan** [comment]
@dsharinov Thanks for the example and detail explanations :D I'll check it.

**Comment by liweinan** [comment]
Sorry I was working on some other tasks, I'll try to find time to check this during this week.

**Comment by liweinan** [comment]
@dsharinov I deployed the project to Tomcat 11 and it seems it doesn't have problem:

![image](https://github.com/resteasy/resteasy-spring-boot/assets/201907/03879aa8-4e91-4d5f-bc59-83909009c321)

The Tomcat version I used is:

- https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.0-M18/bin/apache-tomcat-11.0.0-M18.zip

**Comment by dsharinov** [comment]
@liweinan Thanks! That's good to know, unfortunately it's still an alpha version. I cannot tell customers to install it. Would it still be possible to ignore registration failures and see if it works on Tomcat 10?

**Comment by liweinan** [comment]
> @liweinan Thanks! That's good to know, unfortunately it's still an alpha version. I cannot tell customers to install it. Would it still be possible to ignore registration failures and see if it works on Tomcat 10?

I haven't tested it on Tomcat 10. I'll verify this.

**Comment by liweinan** [comment]
@dsharinov I tested it on Tomcat 10 and the example also works:

![image](https://github.com/resteasy/resteasy-spring-boot/assets/201907/a233b9b6-21f9-4378-9fa6-0bba9225c805)

The tomcat I used is:

- https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.20/bin/apache-tomcat-10.1.20.zip

**Comment by liweinan** [comment]
I assume this issue is answered. Please reopen it if the problem exists.
